### ISSUE TITLE
Cannot run the tests

### ISSUE THREAD

**Issue by adashst** [dan-lee/react-minimal-starter-kit#23] opened 2018-02-05 13:23 UTC
When running the tests with `yarn test`, an `Unexpected token import` error occurs, because import is not transpiled.

I have to run the tests in testing-environment.
so my `package.json` looks like:
```
scripts: {
    "test": "export NODE_ENV=testing && jest"
}
```
and the `.babelrc` is:
```
"env": {
    "testing": {
      "presets": ["env", "react"]
    }
  }
```
See also: https://github.com/facebook/jest/issues/3202

**Comment by dan-lee** [comment] 2018-02-05 14:26
Thank you for reporting this, I definitely can reproduce this. But alas it's not fixed with your suggestion. That's strange, because tests where running fine before 🤔

**Comment by adashst** [comment] 2018-02-05 15:56
I use following versions `"babel-jest": "22.1.0"` and `"jest": "22.1.4"`
I found, that its enough for me to change `test` in  `.babelrc` to `testing`.
Then the tests work.

**Comment by dan-lee** [comment] 2018-02-10 16:09
Should now be fine with the latest packages installed.

**Closed by dan-lee** 2018-02-10 16:09 UTC
